.\"  -*- nroff -*-
.\"
.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.\" Copyright (C) 2004       Shaul Karl.
.\" Copyright (C) 2010-2015  Joachim Nilsson.
.\"
.\" You may modify and distribute this document for any purpose, as
.\" long as this copyright notice remains intact.
.\"
.Dd July 14, 2015
.Dt INADYN 8 SMM
.Os
.Sh NAME
.Nm inadyn
.Nd a small DDNS client to ease your presence on the Internet
.Sh SYNOPSIS
.Nm inadyn
.Op Fl n, -foreground
.Op Fl p, -drop-privs=USER Ns Op : Ns Ar GROUP
.Op Fl e, -exec=/path/to/cmd
.Op Fl f, -config=FILE
.Op Fl h, -help
.Op Fl l, -syslog
.Op Fl 1, -once
.Op Fl t, -startup-delay=SEC
.Op Fl v, -version
.Op Fl V, -verbose
.Sh DESCRIPTION
.Nm
lets you have a public Internet name for your DHCP/PPPoE assigned
system.  It is a client for
.Dq open
name servers, also known as DDNS service providers, such as
.Aq http://dyn.com .
Some of these services are free of charge for non-commercial use, others
take a small fee, but also provide more domains to choose from.
.Pp
Common DDNS service providers supported by
.Nm :
.Pp
.Bl -bullet -compact
.It
.Aq http://www.dyndns.org
a.k.a.
.Aq http://dyn.com
.It
.Aq http://freedns.afraid.org
.It
.Aq http://zoneedit.com
.It
.Aq http://www.no-ip.com
.It
.Aq http://www.easydns.com
.It
.Aq http://www.tzo.com
.It
.Aq http://www.3322.org
.It
.Aq http://www.dnsomatic.com
.It
.Aq http://www.tunnelbroker.net
.It
.Aq http://dns.he.net
.It
.Aq http://www.dynsip.org
.It
.Aq http://www.sitelutions.com
.It
.Aq http://www.dnsexit.com
.It
.Aq http://www.changeip.com
.It
.Aq http://www.zerigo.com
.It
.Aq http://www.dhis.org
.It
.Aq https://nsupdate.info
.It
.Aq http://duckdns.org
.It
.Aq https://www.loopia.com
.It
.Aq https://www.namecheap.com
.It
.Aq https://domains.google.com
.It
.Aq https://www.ovh.com
.It
.Aq https://www.dtdns.com
.It
.Aq http://giradns.com
.It
.Aq https://www.duiadns.net
.El
.Pp
DDNS providers not listed here, like
.Aq http://twoDNS.de ,
can often be configured using the generic DDNS provider plugin.  See
.Xr inadyn.conf 5
for example configurations.
.Pp
.Nm
periodically checks if the actual Internet accessible IP of your system
is the same one that is recorded in the name server, if not
.Nm
updates your name server record(s).
.Sh OPTIONS
Earlier versions of
.Nm
supported more command line options, from v2.0
.Nm
has been greatly simplified.  See
.Xr inadyn.conf 5
for defails of the
.Pa /etc/inadyn.conf
configuration file format.
.Pp
.Bl -tag -width Ds
.It Fl h, -help
Print a summary of the options and exit
.It Fl f, -config Ar FILE
The file name for the
.Nm inadyn
configuration.  The default configuration file name,
.Pa /etc/inadyn.conf ,
is looked at automatically if
.Nm inadyn
is called without any command line options. The syntax is defined in
.Xr inadyn.conf 5
.It Fl n, -forground
Run in foreground, default is to daemonize and background.
.It Fl V, -verbose
Enable verbose logging.
.It Fl l, -syslog
Use the system
.Xr syslog 3
mechanism for log messages, warnings and error conditions.
.It Fl d, -drop-privs=USER Ns Op : Ns Ar GROUP
Drop privileges after initial setup to the given user and group.
.It Fl t, -startup-delay=SEC
option to ensure that an NTP client has set the device's clock before a
cache file is created or read.
.It Fl e, -exec=/path/to/cmd
Full path to command, or script, to run after a successful DDNS update.
The following environment variables are set: INADYN_IP, INADYN_HOSTNAME.
First environment variable contains new IP address, second one - host
name alias.
.It Fl t, -startup-delay Ar SEC
Initial delay at program startup.  Default is 0 seconds.  Any signal can
be used to abort the startup delay early, but SIGUSR2 is the recommended
to use.  See
.Sx SIGNALS
below for full details of how
.Nm
responds to signals.
.Pp
Intended to allow time for embedded devices without a battery backed
real time clock to set their clock via NTP at bootup.  This is so that
the time since the last update can be calculated correctly from the
cache file and the
.Cm forced-update=SEC
setting honored across reboots, avoiding unnecessary IP address updates.
.It Fl 1, -once
Force one update and quit
.El
.Sh OUTPUT
.Nm
prints a message when the IP is updated.  If no update is needed then by
default it prints a single
.Dq .\&
character, unless
.Fl -verbose
is set to
.Ar 0 .
Therefore, unless
.Fl -verbose
is set to
.Ar 0 ,
the log file will contains lot
of dots. When the connection goes down it could be that
.Nm
will print some error messages. Those are harmless and should be
followed by
.Dq OK
messages after the connection is back up.
.Sh SIGNALS
.Nm
responds to the following signals:
.Pp
.Bl -tag -width TERM -compact
.It HUP
Reload the
.Nm .conf 
file, standard UNIX behavior
.It TERM
Tell
.Nm
to exit gracefully
.It INT
Same as TERM
.It USR1
Force update now, even if the IP address has not changed.  Works in
tandem with
.Fl -fake-address
.It USR2
Check IP address change now. Useful when a new DHCP/PPPoE lease or new
gateway is received.  Please note that
.Nm
does not track such events by itself.  You need an external monitor for
that
.El
.Pp
For convenience in sending signals,
.Nm
writes its process ID to
.Pa /var/run/inadyn.pid
.Sh FILES
.Bl -tag -width /var/cache/inadyn/freedns.afraid.org.cache -compact
.It Pa /etc/inadyn.conf
.It Pa /var/run/inadyn.pid
.It Pa /var/cache/inadyn/dyndns.org.cache
.It Pa /var/cache/inadyn/freedns.afraid.org.cache
.It Pa ... one .cache file per DDNS provider
.El
.Sh SEE ALSO
.Xr inadyn.conf 5
.Pp
The
.Nm
home page is at GitHub:
.Aq https://github.com/troglobit/inadyn
.Sh AUTHORS
.Nm
was originally written by
.Bl -bullet -compact
.It
Narcis Ilisei
.Aq mailto:inarcis2002@hotpop.com
and
.It
Steve Horbachuk
.El
.Pp
It is now maintained at GitHub by
.Bl -bullet -compact
.It
Joachim Nilsson
.Aq mailto:troglobit@gmail.com
with a lot of help from
.It
Andrey Tikhomirov, and
.It
Mike Fleetwood
.El
.Pp
This manual page was originally written for the
.Em Debian GNU/Linux
project by
.An -nosplit
.An Shaul Karl Aq mailto:shaul@debian.org .
Currently maintained by
.An -nosplit
.An Joachim Nilsson.
